version: "3.9"
services:
    base:
        entrypoint: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"] #["python ${INSTALL_ROOT}/scripts/fp8_test.py"] #
        image: rocm/pytorch:rocm6.1_ubuntu22.04_py3.10_pytorch_2.4
        hostname: test
        environment:
            - USE_HTTPS=0
            - INSTALL_ROOT=${INSTALL_ROOT}
        ports:
            - "5001:5001"
        volumes:
            - type: bind
              source: scripts
              target: ${INSTALL_ROOT}/scripts
            - type: bind
              source: models
              target: ${INSTALL_ROOT}/models
            - type: bind
              source: libraries
              target: ${INSTALL_ROOT}/libraries
            #   read_only: true
        devices:
            - /dev/kfd
            - /dev/dri
        group_add:
            - video
        ipc: host
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp=unconfined

networks:
  llama-network:
    name: llama_backend_network


